import type { NextPage } from "next";
import Head from "next/head";
import HomeComponent from "../components/Home/Home.component";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <HomeComponent />
      </>
    </div>
  );
};

export default Home;
