import type { NextPage } from "next";
import Head from "next/head";
import LoginComponent from "../components/Login/Login.component";

const Login: NextPage = (): JSX.Element => {
  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <LoginComponent />
      </>
    </div>
  );
};

export default Login;
